### ISSUE TITLE
 this feature requires an iOS Developer Disk Image to be mounted; run Xcode briefly or use ideviceimagemounter to mount one manually

### ISSUE THREAD

**Issue by dakezuo** [frida/frida#1202]
Device:

iOS 13.2.3 (unc0ver-jailbroken)
Software:

OSX 10.15.2
Frida 12.8.13 

frida-ps -U
Failed to enumerate processes: this feature requires an iOS Developer Disk Image to be mounted; run Xcode briefly or use ideviceimagemounter to mount one manually
and device restart

**Comment by l0gg3r** [comment]
same issue for me

**Comment by oleavr** [comment]
Please specify what kind of device you're using. A12/A13 devices are not yet supported.

**Comment by l0gg3r** [comment]
@oleavr iPhone X with 13.3 unc0ver
Yes, seems related to https://github.com/frida/frida/issues/885

**Comment by oleavr** [comment]
@l0gg3r iPhone X is pre-A12, so that means you're running into an unc0ver-specific issue. (And that will indeed be solved as part of solving #885.)

**Comment by oleavr** [comment]
@l0gg3r You can use [checkra1n](https://checkra.in/) in the meantime, as it's a supported jailbreak.

**Comment by l0gg3r** [comment]
@oleavr thanks, it worked with checkra1n

**Comment by dakezuo** [comment]
@oleavr iPhone6s with 13.2.3 unc0ver

**Comment by oleavr** [comment]
@dakezuo Please use checkra1n until we've finished adding support for the latest unc0ver.

**Comment by rustymagnet3000** [comment]
hey, did you check the `Frida-Server` was running on the device?
```
ps -ax | grep -i frida
  436 ttys000    0:00.04 ./frida-server
```
I was happily running `Electra` (jailbreak) with `Tweaks`.  All fine.  Then I re-started the device.  

I re-applied the `Jailbreak with NO tweaks` and i hit this message.

`frida-server` did not auto-run when `Tweaks` were  off.

Just `ssh` into the device and `/usr/sbin root# ./frida-server &`

**Comment by flashlizi** [comment]
I got this issue too.
--------
iPad mini 4
iOS 13.5
macOS 10.15.4
Frida 12.9.4

**Comment by oleavr** [comment]
It means the server isn't running, so Frida assumes the device isn't jailbroken and will fall back to the jailed codepaths (which require the Developer Disk Image to be mounted).

**Comment by akashkatare** [comment]
i am running iphone 6 version 12.4.8 and jailbroken the phone using checkra1n  but still i am getting same issue "Failed to enumerate processes: this feature requires an iOS Developer Disk Image to be mounted; run Xcode briefly or use ideviceimagemounter to mount one manually"   need help asap 
thanks in adv

**Comment by JeakinsCheung** [comment]
我也是遇到这种问题,怎么解决

**Comment by flamecopper** [comment]
i just faced this issue,
I am using Ipad mini 3, 11.3
Now using frida 12.4.8
Was working awhile ago, now not working.

**Comment by flamecopper** [comment]
/usr/sbin root# ps -ax | grep -i frida
  658 ??         0:00.68 /usr/sbin/frida-server
  682 ttys001    0:00.03 grep -i frida
Westons-iPad:/usr/sbin root# ./frida-server & 
[1] 683

for me it was already started.

**Comment by oleavr** [comment]
Recommend getting the latest updates in Cydia, and then trying with Frida 15.0.8. We have just added support for the latest checkra1n and unc0ver jailbreaks – but we only support the latest version of Substrate/Substitute.

**Comment by flamecopper** [comment]
I have already install frida 15.0.8 both on my ipad and linux.
And it is still not working. 
Now I shall try upgrading Substrate/Substitute,

**Comment by flamecopper** [comment]
I just upgraded substrate to 2.0.11 still not working.
Please help its urgent.

**Comment by flamecopper** [comment]
Unable to start: Could not listen on address 127.0.0.1, port 27042: Error binding to address 127.0.0.1:27042: Address already in use frida

**Comment by oleavr** [comment]
@flamecopper Latest Substrate was 0.9.7113 last I checked, so that sounds wrong.  Anyway, you shouldn't start frida-server yourself, the launchd plist included in the package starts it automatically. So now if it doesn't work it's probably because it's crashing the first time you connect to it. Check if the frida-server's PID changes or stays the same, and look for crash reports (e.g. using Xcode).

**Comment by flamecopper** [comment]
My substrate is currently now 0.97113.

/usr/sbin root# ./frida-server &
[1] 1662
Westons-iPad:/usr/sbin root# **
Frida:ERROR:../../../frida-core/src/darwin/springboard.m:66:_frida_get_springboard_api: assertion failed: (api->LSApplicationProxy != nil)
Bail out! Frida:ERROR:../../../frida-core/src/darwin/springboard.m:66:_frida_get_springboard_api: assertion failed: (api->LSApplicationProxy != nil)
Westons-iPad:/usr/sbin root#

**Comment by oleavr** [comment]
Aha! So we're depending on an API that's too new for iOS 11.3 – oops. The unfortunate news is that I'm on vacation and I don't have any iOS devices to test with, so I'm afraid you'll have to fix this on your end and open a PR.

**Comment by flamecopper** [comment]
Westons-iPad:/usr/sbin root# ps -ax | grep frida
 1731 ttys000    0:00.06 ./frida-server
 1740 ttys000    0:00.03 grep frida
Westons-iPad:/usr/sbin root# ps -ax | grep frida
 1731 ttys000    0:00.06 ./frida-server
 1742 ttys000    0:00.04 grep frida
Westons-iPad:/usr/sbin root# ps -ax | grep frida
 1731 ttys000    0:00.06 ./frida-server
 1745 ttys000    0:00.02 grep frida
Westons-iPad:/usr/sbin root# **
Frida:ERROR:../../../frida-core/src/darwin/springboard.m:66:_frida_get_springboard_api: assertion failed: (api->LSApplicationProxy != nil)
Bail out! Frida:ERROR:../../../frida-core/src/darwin/springboard.m:66:_frida_get_springboard_api: assertion failed: (api->LSApplicationProxy != nil)

**Comment by flamecopper** [comment]
> Aha! So we're depending on an API that's too new for iOS 11.3 – oops. The unfortunate news is that I'm on vacation and I don't have any iOS devices to test with, so I'm afraid you'll have to fix this on your end and open a PR.

but this is the first time I faced this issues, was it because of the update that cause this to work?

**Comment by oleavr** [comment]
It's a regression in Frida 15, where we're accidentally depending on newer iOS than what your device is running. The failing assertion contains filename and line number info in case you want to take a stab at fixing it (it's in frida-core, but clone the frida repo as per the docs to build it).

**Comment by flamecopper** [comment]
ok, so can u tell me what is the safest version I can update to and I can still use unc0ver? 
Anyway I have tried 14.2.18, it is still not working for me.

**Comment by oleavr** [comment]
There isn't any, unc0ver support was fixed in Frida 15.

**Comment by flamecopper** [comment]
I mean ios version (to be clear) I am currently using 11.3.

**Comment by oleavr** [comment]
unc0ver supports 11.0 - 14.3. I know Frida 15 has been tested successfully on 14.x and 15 beta 2.

**Comment by flamecopper** [comment]
I have just reproduce the issue by using an older version of frida 12.2.7. And it works fine.

Frida 15 should not support newer version. 
Some developer/tester are using older version of Iphone so that they can install certain legacy tools from cydia to work on the IPad.
Hope you can make the change to allow Frida 15 to support 11+ onwards.

**Comment by spookey0188** [comment]
Running Checkra1n on iphone 6s ver 14.4.1 and can confirm I get the same error, "this feature requires an iOS Developer Disk Image to be mounted; run Xcode briefly or use ideviceimagemounter to mount one manually". At first, it just hangs/freezes, but when I unplug the iPhone it gives the error message. It seems Frida 15 doesn't work well on 14.x+ jailbroken devices. Waiting for a fix soon.

**Comment by oleavr** [comment]
@spookey0188 Make sure you install the correct package. (You can double-check the version by SSHing to the device and running `frida-server --version` or `dpkg -l | grep frida`.) Also make sure you install all package updates – we only support the latest version of Substrate, so if your system has an outdated version, things won't work.

**Comment by oleavr** [comment]
@flamecopper Latest Frida 15 has restored support for older iOS versions. There's also a bunch of other very fixes, so make sure you try the latest version. (15.0.13 currently.)

**Comment by spookey0188** [comment]
> spookey0188 Would recommend checking that:
> 
> 1. The correct package is installed. You can double-check the version by SSHing to the device and running `frida-server --version` or `dpkg -l | grep frida`.
Yes I can confirm its running the latest 15.0.13

@oleavr 
<img width="433" alt="frida bad" src="https://user-images.githubusercontent.com/11284797/127726145-01267f97-9216-49fb-9312-bb143549f600.PNG">


> 2. All package are up-to-date. We only support the latest version of Substrate, so if your system has an outdated version, things won't work.

All my packages are up to date and have the latest ver of Substrate installed. When I run `frida-ps -U` it just freezes. It doesn't seem that 15.0.13 fixed the problem for older versions, unfortunately. 

<img width="309" alt="frida 2" src="https://user-images.githubusercontent.com/11284797/127726144-af3ce61f-3b56-4a65-8505-58d3d3977ade.PNG">

**Comment by spookey0188** [comment]
@oleavr is it possible to downgrade to a older version of Frida via cydia? Hoping a older version will work since version 15 isn't working.

**Comment by oleavr** [comment]
@spookey0188 I also have an iPhone 6S with checkra1n, and it works great on 14.7.1. Try a DFU restore and then re-jailbreak – there's probably some cruft left on the system that's breaking things. (Downgrade isn't advisable as lots of bugs have been fixed in 15.)

**Comment by spookey0188** [comment]
> @spookey0188 I also have an iPhone 6S with checkra1n, and it works great on 14.7.1. Try a DFU restore and then re-jailbreak – there's probably some cruft left on the system that's breaking things. (Downgrade isn't advisable as lots of bugs have been fixed in 15.)

I did a DFU restore, updated to 14.7.1, re jailbroke it with checkra1n, and it STILL doesn't work. I get the same exact error.

**Comment by oleavr** [comment]
@spookey0188 Then the issue must be on the host side. Check that:
1. Frida is the latest version. (Major versions must match.) If you're using the CLI tools, check using `frida --version`.
2. Connection is made over USB. We also support networked iOS devices, but that requires editing the launchd .plist on the device side to add `--listen=x` so frida-server doesn't only listen on loopback.

**Comment by Am1nCmd** [comment]
> @spookey0188 Then the issue must be on the host side. Check that:
> 
> 1. Frida is the latest version. (Major versions must match.) If you're using the CLI tools, check using `frida --version`.
> 2. Connection is made over USB. We also support networked iOS devices, but that requires editing the launchd .plist on the iOS side to add `--listen=x` so frida-server doesn't only listen on loopback.

hi there, I also have this issue but after try to make sure using the same version 15.0.15 its running, but the next problem is "target process died unexpectedly" 
<img width="617" alt="image" src="https://user-images.githubusercontent.com/15339573/129953937-16f352a7-3f6e-4c97-8e5b-9ca6378a5923.png">

I'm using iPhone 11 running iOS 14.3 with unc0ver jailbreak

another question, does it support with Taurine > LibHooker?

**Comment by flashgg2017** [comment]
> 我也是遇到这种问题,怎么解决

cydia添加源http://build.frida.re/，并安装frida，你会回来感谢我的！

**Comment by yilongmd** [comment]
I also have such a problem. But I installed Frida instead of A12 + to solve the problem

**Comment by bx1n** [comment]
Dropping in my issue and fix - although my phone had the latest version of Frida, my system was running an older version of Frida and frida-tools. Upgrading Frida on system and reinstalling Frida on phone worked

**Comment by RazviAlex** [comment]
In case it works for someone, before re-installing a jailbreak on an iOS 12.5.5 - iPhone 6, it worked perfectly. But after that re-installing same thing happened to me as the initial message. Tried one more time to erase and reset the device, also re-install the jailbreak , but it still the same, `frida-ps -U` stayed frozen.

So the next thing was to **remove frida from the computer and reinstall it**, and everything went back to working correctly with the last version.

**Comment by g2asell2019** [comment]
`So the next thing was to remove frida from the computer and reinstall it, now everything went back to working correctly with the last version.`

Did you use pip `uninstall ` to remove frida?

**Comment by RazviAlex** [comment]
> Did you use pip `uninstall ` to remove frida?

Yes, with pip uninstall

**Comment by JordanA54** [comment]
> Dropping in my issue and fix - although my phone had the latest version of Frida, my system was running an older version of Frida and frida-tools. Upgrading Frida on system and reinstalling Frida on phone worked

非常有用，感谢！

**Comment by maelp** [comment]
I have the issue on Sequoia with non-jailbroken iPhone 11 with latest iOS

**Comment by flamecopper** [comment]
I just want to check with you if you have shadow actually turn on. And what
is the setting that you actually turn on

**Comment by maelp** [comment]
@flamecopper what is "shadow" ?

**Comment by flamecopper** [comment]
It is a form of tweaks available in iOS.
Do check if you have other tweaks interfering with this
