### ISSUE TITLE
frida-server: can't execute: Is a directory

### ISSUE THREAD

**Issue by imran209** [frida/frida#1269]
Hi,
@oleavr I was setting up Frida-server on the android rooted device and do all these steps
$ adb push frida-server /data/local/tmp/
$ adb shell "chmod 755 /data/local/tmp/frida-server"
$ adb shell "/data/local/tmp/frida-server &"

C:\U###s\P###A\AppData\Local\Android\Sdk\platform-tools>adb shell /data/local/tmp/frida-server &
/system/bin/sh: /data/local/tmp/frida-server: can't execute: Is a directory

and also the following

C:\U###s\P###A\AppData\Local\Android\Sdk\platform-tools>adb shell
shell@kenzo:/ $ su
root@kenzo:/ # /data/local/tmp/frida-server &
[1] 6687
root@kenzo:/ # sush: /data/local/tmp/frida-server: can't execute: Is a directory

Please let me know how to solve this.

Regards,
Imran

**Comment by wengxianxun** [comment]
? why closed, no answer?

**Comment by coder-Silver** [comment]
？？？ 咋关了 ，咋解决的 ？

**Comment by RaduStavilaGG** [comment]
Somebody should just make a step by step tutorial including SS or make a damn video cuz this is all a headache. Legit everyone deals with these issues and hardly get an answer. I also cannot bypass this step whichever folder I download it just won't work. It's all a useless tool unless you provide a CLEAR STEP BY STEP TUTORIAL.

**Comment by samiparyal** [comment]
You might have downloaded this 
![image](https://user-images.githubusercontent.com/84836995/233346562-2c45172c-ace8-4118-b657-605ad1f510a3.png)
instead of this:
![image](https://user-images.githubusercontent.com/84836995/233346707-8d9df472-17bc-452c-9099-2c03358d1e94.png)
1. Download this one (second pic) one and then extract the folder where you will see only one file, 
2. use these commands: 
`adb push frida-server-16.0.17-android-x86 /data/local/tmp`

[Still the problem might not have been solved because the previous devkit files might still be in /data/local/tmp so it might be hindering the process, thus delete all those previous files]

3. `adb shell`
4. `cd /data/local/tmp`
5. `ls`
6. ` rm -r frida-core-devkit-16.0.17-android-x86.tar` and similarly rm -r <other unnecessary files>
7.  `chmod 777 frida-server`
8.  `./frida-server`

You are good to go!

**Comment by blackerhot** [comment]
if u are using x64 windows, plz make sure u download x86_64 frida-server< this sovleed me

**Comment by iremnurylmz** [comment]
Solution:
1.  pip install frida-tools
2. adb shell getprop ro.product.cpu.abi 
3. https://github.com/frida/frida/releases/tag/16.4.10 
Download frida-server from this address according to the output in step 2.

4. adb push frida-server-16.4.10-android-x86_64 /data/local/tmp/frida-server
5. adb shell “chmod 755 /data/local/tmp/frida-server”
6. adb shell “/data/local/tmp/frida-server &”

**Comment by iremnurylmz** [comment]
> Birisi SS'yi de içeren adım adım bir eğitim hazırlamalı veya lanet bir video yapmalı çünkü bunların hepsi baş ağrısı. Gerçekten herkes bu sorunlarla uğraşıyor ve neredeyse hiç cevap alamıyor. Ben de bu adımı atlayamıyorum, hangi klasörü indirirsem indireyim işe yaramıyor. NET BİR ADIM ADIM EĞİTİM sağlamadığınız sürece hepsi işe yaramaz bir araç.

https://github.com/iremnurylmz/mobile_app_security

**Comment by dracula74644** [comment]
I'm still getting the error. 
-rwx------ 1 root  root  108M 2024-10-10 00:57 frida
genymotion:/data/local/tmp # ./frida
/system/bin/sh: ./frida: No such file or directory
