### ISSUE TITLE
Failed to attach: remote_write PTRACE_POKEDATA head failed: 5

### ISSUE THREAD

**Issue by SergeyAppDroid** [frida/frida#910]
I am use frida 12.2.30 for real device Huawei Honor 7aPro Android 8.0.0, arm64-v8a.

When trying to attach to the process, an error occurs:
```
os@os:~$ frida-trace -i "open" -U com.android.phone
Failed to attach: remote_write PTRACE_POKEDATA head failed: 5  
```
I tried all the methods for solving this problem described earlier. I have installed Magisk and modules: MagiskHideProps Config and Magisk SELinux Permissive Script. 
I have installed Xposed with module BuildProp Enhancer.

But my problem is still not solved. Please help me!

**Comment by oleavr** [comment]
Please avoid reporting bugs for old versions of Frida – it is a waste of everybody's time, yours included (as the bug may already be fixed).

**Comment by SergeyAppDroid** [comment]
@oleavr Ok!
Now I am using the latest version:
```
os@os:~$ pip show frida
Name: frida
Version: 12.6.5
Summary: Dynamic instrumentation toolkit for developers, reverse-engineers, and security researchers
Home-page: https://www.frida.re
Author: Frida Developers
Author-email: oleavr@frida.re
License: wxWindows Library Licence, Version 3.1
Location: /usr/local/lib/python3.5/dist-packages
Requires: 
Required-by: objection, frida-tools
```
But the problem did not dare. Please open the my issue again.

**Comment by oleavr** [comment]
Did you also update Frida on your Android device?

**Comment by SergeyAppDroid** [comment]
@oleavr Of course. I use this [server](https://github.com/frida/frida/releases/download/12.6.5/frida-server-12.6.5-android-arm64.xz)

**Comment by oleavr** [comment]
Ok. This is a ROM-specific issue. I will reopen the issue but there's unfortunately not much that can be done without somebody investigating this issue on a device like yours.

**Comment by SergeyAppDroid** [comment]
@oleavr Perhaps the problem is with the device huawei? You did not have experience with the device manufacturer?

**Comment by oleavr** [comment]
Yeah this is definitely a device/ROM-specific issue. My only available test devices are Pixel 3, Nexus 5X, and Samsung S6 Edge.

**Comment by SergeyAppDroid** [comment]
@oleavr In addition, as far as I know, the Xposed conflicts with the Magisk within root-permissions which probably does not allow the frida to start as root

**Comment by oleavr** [comment]
No idea. We don't currently do any interoperability testing with Xposed. There's too many combinations to test, the test matrix is just insane, so we keep things simple: Google/Nexus devices are supported, everything else: here's the source-code, help us make it better ;-)

**Comment by SergeyAppDroid** [comment]
@oleavr I think you need to pay attention to Chinese manufacturers in the future. The popularity of these devices is much more than any Google/Nexus ))

**Comment by SergeyAppDroid** [comment]
@oleavr What does this error mean?
`remote_write PTRACE_POKEDATA head failed: 5`

**Comment by SergeyAppDroid** [comment]
perhaps logging will be useful

```
2019-06-05 14:22:26.413 1157-1157/? W//system/bin/chargemonitor: Waited for hwservicemanager.ready for a second, waiting another...
2019-06-05 14:22:26.414 1157-1157/? E/libc: Access denied finding property "hwservicemanager.ready"
2019-06-05 14:22:26.414 1157-1157/? E/libc: Access denied finding property "hwservicemanager.ready"
2019-06-05 14:22:27.414 1157-1157/? W//system/bin/chargemonitor: Waited for hwservicemanager.ready for a second, waiting another...
2019-06-05 14:22:27.414 1157-1157/? E/libc: Access denied finding property "hwservicemanager.ready"
2019-06-05 14:22:27.414 1157-1157/? E/libc: Access denied finding property "hwservicemanager.ready"
2019-06-05 14:22:28.413 1157-1157/? W/chargemonitor: type=1400 audit(0.0:4219): avc: denied { read } for name="u:object_r:hwservicemanager_prop:s0" dev="tmpfs" ino=496 scontext=u:r:chargemonitor:s0 tcontext=u:object_r:hwservicemanager_prop:s0 tclass=file permissive=0
2019-06-05 14:22:28.415 1157-1157/? W//system/bin/chargemonitor: Waited for hwservicemanager.ready for a second, waiting another...
2019-06-05 14:22:28.415 1157-1157/? E/libc: Access denied finding property "hwservicemanager.ready"
2019-06-05 14:22:28.415 1157-1157/? E/libc: Access denied finding property "hwservicemanager.ready"
2019-06-05 14:22:29.416 1157-1157/? W//system/bin/chargemonitor: Waited for hwservicemanager.ready for a second, waiting another...
2019-06-05 14:22:29.416 1157-1157/? E/libc: Access denied finding property "hwservicemanager.ready"
2019-06-05 14:22:29.416 1157-1157/? E/libc: Access denied finding property "hwservicemanager.ready"
2019-06-05 14:22:29.979 9938-10110/? D/HwBatteryService: onUEvent fcpStatus = 0,scpStatus =0,ovpStatus=0
2019-06-05 14:22:30.413 1157-1157/? I/chatty: uid=1000(system) /system/bin/chargemonitor identical 2 lines
2019-06-05 14:22:30.413 1157-1157/? W/chargemonitor: type=1400 audit(0.0:4224): avc: denied { read } for name="u:object_r:hwservicemanager_prop:s0" dev="tmpfs" ino=496 scontext=u:r:chargemonitor:s0 tcontext=u:object_r:hwservicemanager_prop:s0 tclass=file permissive=0
2019-06-05 14:22:30.416 1157-1157/? W//system/bin/chargemonitor: Waited for hwservicemanager.ready for a second, waiting another...
2019-06-05 14:22:30.416 1157-1157/? E/libc: Access denied finding property "hwservicemanager.ready"
2019-06-05 14:22:30.416 1157-1157/? E/libc: Access denied finding property "hwservicemanager.ready"
2019-06-05 14:22:31.416 1157-1157/? W//system/bin/chargemonitor: Waited for hwservicemanager.ready for a second, waiting another...
2019-06-05 14:22:31.417 1157-1157/? E/libc: Access denied finding property "hwservicemanager.ready"
2019-06-05 14:22:31.417 1157-1157/? E/libc: Access denied finding property "hwservicemanager.ready"
2019-06-05 14:22:32.417 1157-1157/? W//system/bin/chargemonitor: Waited for hwservicemanager.ready for a second, waiting another...
2019-06-05 14:22:32.417 1157-1157/? E/libc: Access denied finding property "hwservicemanager.ready"
2019-06-05 14:22:32.417 1157-1157/? E/libc: Access denied finding property "hwservicemanager.ready"
2019-06-05 14:22:33.417 1157-1157/? W//system/bin/chargemonitor: Waited for hwservicemanager.ready for a second, waiting another...
2019-06-05 14:22:33.417 1157-1157/? E/libc: Access denied finding property "hwservicemanager.ready"
2019-06-05 14:22:33.417 1157-1157/? E/libc: Access denied finding property "hwservicemanager.ready"
2019-06-05 14:22:34.417 1157-1157/? W//system/bin/chargemonitor: Waited for hwservicemanager.ready for a second, waiting another...
2019-06-05 14:22:34.418 1157-1157/? E/libc: Access denied finding property "hwservicemanager.ready"
2019-06-05 14:22:34.418 1157-1157/? E/libc: Access denied finding property "hwservicemanager.ready"
2019-06-05 14:22:34.803 888-1076/? I/qti_sensors_hal: [LightSensor]processReportInd: the cycle luxValue ItemData[0]:230000,ItemData[1]:9d, lux:35.000000,cct:0.002396
2019-06-05 14:22:35.418 1157-1157/? W//system/bin/chargemonitor: Waited for hwservicemanager.ready for a second, waiting another...
2019-06-05 14:22:35.418 1157-1157/? E/libc: Access denied finding property "hwservicemanager.ready"
2019-06-05 14:22:35.418 1157-1157/? E/libc: Access denied finding property "hwservicemanager.ready"
2019-06-05 14:22:35.662 15913-15913/? I/appproc: CLASSPATH=/system/framework/am.jar
2019-06-05 14:22:35.663 15913-15913/? I/appproc: Command=/system/bin/app_process /system/bin com.android.commands.am.Am broadcast -n com.topjohnwu.magisk/a.h --user 0 -f 0x00000020 -a android.intent.action.REBOOT --es action log --ei from.uid 2000 --ei to.uid 0 --ei pid 15907 --ei policy 2 --es command id --ez notify true 
2019-06-05 14:22:35.663 15913-15913/? D/AndroidRuntime: >>>>>> START com.android.internal.os.RuntimeInit uid 0 <<<<<<
2019-06-05 14:22:35.667 15913-15913/? I/AndroidRuntime: readDownloadBoosterConfig: 'false'
2019-06-05 14:22:35.814 15913-15913/? V/HwFrameworkFactory: : successes to get AllImpl object and return....
2019-06-05 14:22:35.828 15913-15913/? I/HWSERVICES: hwnative_get_component_register:libdrmbitmap,JNI
2019-06-05 14:22:35.854 15913-15913/? E/Zygote: register_com_android_internal_os_Zygote num = 0
2019-06-05 14:22:35.869 15913-15913/? D/AndroidRuntime: Calling main entry com.android.commands.am.Am
2019-06-05 14:22:35.872 1101-1173/? W/SchedPolicy: add_tid_to_cgroup failed to write '15921' (Permission denied); fd=6
2019-06-05 14:22:35.872 1101-1173/? E/SchedPolicy: set_cpuset_policy failed err=-22, tid=15921, policy=1
2019-06-05 14:22:35.873 1101-1173/? W/SchedPolicy: add_tid_to_cgroup failed to write '15921' (Permission denied); fd=6
2019-06-05 14:22:35.873 1101-1173/? E/SchedPolicy: set_cpuset_policy failed err=-22, tid=15921, policy=1
2019-06-05 14:22:35.874 1101-1173/? W/SchedPolicy: add_tid_to_cgroup failed to write '15922' (Permission denied); fd=6
2019-06-05 14:22:35.874 1101-1173/? E/SchedPolicy: set_cpuset_policy failed err=-22, tid=15922, policy=1
2019-06-05 14:22:35.874 1101-1173/? W/SchedPolicy: add_tid_to_cgroup failed to write '15922' (Permission denied); fd=6
2019-06-05 14:22:35.874 1101-1173/? E/SchedPolicy: set_cpuset_policy failed err=-22, tid=15922, policy=1
2019-06-05 14:22:35.904 13994-13994/? D/HwRTBlurUtils: check blur style for HwToast-Toast, themeResId : 0x0103013f, context : a.e@da8688b, Nhwext : 6, get Blur : disable with , android.graphics.drawable.NinePatchDrawable@b119b2d
2019-06-05 14:22:35.979 9938-13920/? V/BroadcastQueue: Finished with ordered broadcast BroadcastRecord{786767f u0 android.intent.action.REBOOT}
2019-06-05 14:22:35.981 15913-15913/? D/AndroidRuntime: Shutting down VM
2019-06-05 14:22:35.981 13994-15598/? D/OpenGLRenderer:   HWUI Binary is  disabled
2019-06-05 14:22:35.981 10490-10889/? I/ash: view add pid:13994 uid:10099
2019-06-05 14:22:35.985 9938-13920/? V/WindowManager: Adding Window{415fb9b u0 Toast} to WindowToken{4e78b38 android.os.Binder@7a91695}
2019-06-05 14:22:35.986 9938-13920/? V/WindowManager: addWindow: New client android.os.BinderProxy@41e33aa: window=Window{415fb9b u0 Toast} Callers=com.android.server.wm.HwWindowManagerService.addWindow:585 com.android.server.wm.Session.addToDisplay:199 android.view.IWindowSession$Stub.onTransact:124 com.android.server.wm.Session.onTransact:161 android.os.Binder.execTransact:675 
2019-06-05 14:22:35.987 13994-15598/? D/OpenGLRenderer:   HWUI Binary is  disabled
2019-06-05 14:22:35.989 13994-13994/? W/ViewRootImpl[Toast]: EGLdebug relayoutWindow Surface isSurface(name=null)  (appName =com.topjohnwu.magisk) ( mSurfaceControllerIsValid =false) (mNativeObject  =0)/@0x3a7564f,viewVisibility is0
2019-06-05 14:22:35.995 430-430/? I/SELinux: avc:  received policyload notice (seqno=3)
2019-06-05 14:22:35.996 430-430/? E/SELinux: avc:  denied  { find } for interface=vendor.huawei.hardware.hwsched::ISched pid=907 scontext=u:r:surfaceflinger:s0 tcontext=u:object_r:default_android_hwservice:s0 tclass=hwservice_manager
2019-06-05 14:22:35.996 907-907/? E/BufferQueueProducer: [] Can not get hwsched service
2019-06-05 14:22:35.998 9938-13920/? W/WindowManager: EGLdebug Created surface WindowStateAnimator{8518711 Toast}
2019-06-05 14:22:36.000 9938-13920/? W/WindowManager: EGLdebug surface name is Toastsurface is Surface(name=null)  (appName =null) ( mSurfaceControllerIsValid =true) (mNativeObject  =7c31ad6000)/@0xa03e076
2019-06-05 14:22:36.006 13994-13994/? W/ViewRootImpl[Toast]: EGLdebug relayoutWindow Surface isSurface(name=null)  (appName =com.topjohnwu.magisk) ( mSurfaceControllerIsValid =true) (mNativeObject  =7c61a63000)/@0x3a7564f,relayoutResult is7
2019-06-05 14:22:36.006 13994-13994/? W/ViewRootImpl[Toast]: EGLdebug Surface isSurface(name=null)  (appName =com.topjohnwu.magisk) ( mSurfaceControllerIsValid =true) (mNativeObject  =7c61a63000)/@0x3a7564f
2019-06-05 14:22:36.010 864-864/? E/SDM: DisplayBase::BuildLayerStackStats: LayerStack layer_count: 5, app_layer_count: 4, gpu_target_index: 4, display type: 0
2019-06-05 14:22:36.011 864-864/? E/SDM: Strategy::GetNextStrategy: All strategy failed, falling back to GPU
2019-06-05 14:22:36.028 864-864/? E/SDM: DisplayBase::BuildLayerStackStats: LayerStack layer_count: 5, app_layer_count: 4, gpu_target_index: 4, display type: 0
2019-06-05 14:22:36.028 864-864/? E/SDM: Strategy::GetNextStrategy: All strategy failed, falling back to GPU
2019-06-05 14:22:36.035 9938-13920/? D/WindowManager: finishDrawingWindow: Window{415fb9b u0 Toast} mDrawState=DRAW_PENDING
2019-06-05 14:22:36.044 864-864/? E/SDM: DisplayBase::BuildLayerStackStats: LayerStack layer_count: 5, app_layer_count: 4, gpu_target_index: 4, display type: 0
2019-06-05 14:22:36.044 864-864/? E/SDM: Strategy::GetNextStrategy: All strategy failed, falling back to GPU
2019-06-05 14:22:36.061 1013-3037/? D/DE N SR: setXnit:1056: R=32768 G=32768 B=32768 len=12
2019-06-05 14:22:36.061 864-864/? E/SDM: DisplayBase::BuildLayerStackStats: LayerStack layer_count: 6, app_layer_count: 5, gpu_target_index: 5, display type: 0
2019-06-05 14:22:36.062 1013-2325/? D/DE N ^XNIT: onChange:35: DE_SCENE_ACTION_XNIT_CHANGE COMPONENT_XCC mode:0x1f
2019-06-05 14:22:36.062 1013-2325/? D/DE N HWC: apply:87: FEATURE_XCC: <mode:0x1e>
2019-06-05 14:22:36.062 1013-2325/? D/DE N HW: setEffect:71: FEATURE_XCC mode:0x1e size:12
2019-06-05 14:22:36.065 879-879/? D/DE H =KI: setXCC:93: 3d_color_temperature config: r=32768, g=32768, b=32768
2019-06-05 14:22:36.065 879-879/? D/DE H =KI: setXCC:103: Set pp data of 3d_color_temperature successful!
2019-06-05 14:22:36.077 864-864/? E/SDM: DisplayBase::BuildLayerStackStats: LayerStack layer_count: 6, app_layer_count: 5, gpu_target_index: 5, display type: 0
2019-06-05 14:22:36.210 864-864/? I/chatty: uid=1000(system) composer@2.1-se identical 5 lines
2019-06-05 14:22:36.244 864-864/? E/SDM: DisplayBase::BuildLayerStackStats: LayerStack layer_count: 6, app_layer_count: 5, gpu_target_index: 5, display type: 0
2019-06-05 14:22:36.276 9702-9706/? E/libnav: CablComputeBacklightLevel(): UpdateType = DifferentSceneUpdate
2019-06-05 14:22:36.278 864-864/? E/SDM: DisplayBase::BuildLayerStackStats: LayerStack layer_count: 6, app_layer_count: 5, gpu_target_index: 5, display type: 0
2019-06-05 14:22:36.344 864-864/? E/SDM: DisplayBase::BuildLayerStackStats: LayerStack layer_count: 6, app_layer_count: 5, gpu_target_index: 5, display type: 0
2019-06-05 14:22:36.359 9938-10221/? D/LightsService: Excessive delay setting light: 66ms
2019-06-05 14:22:36.361 864-864/? E/SDM: DisplayBase::BuildLayerStackStats: LayerStack layer_count: 6, app_layer_count: 5, gpu_target_index: 5, display type: 0
2019-06-05 14:22:36.378 864-864/? I/chatty: uid=1000(system) composer@2.1-se identical 1 line
2019-06-05 14:22:36.411 864-864/? E/SDM: DisplayBase::BuildLayerStackStats: LayerStack layer_count: 6, app_layer_count: 5, gpu_target_index: 5, display type: 0
2019-06-05 14:22:36.418 1157-1157/? W//system/bin/chargemonitor: Waited for hwservicemanager.ready for a second, waiting another...
2019-06-05 14:22:36.419 1157-1157/? E/libc: Access denied finding property "hwservicemanager.ready"
2019-06-05 14:22:36.419 1157-1157/? E/libc: Access denied finding property "hwservicemanager.ready"
2019-06-05 14:22:36.413 1157-1157/? W/chargemonitor: type=1400 audit(0.0:4239): avc: denied { read } for name="u:object_r:hwservicemanager_prop:s0" dev="tmpfs" ino=496 scontext=u:r:chargemonitor:s0 tcontext=u:object_r:hwservicemanager_prop:s0 tclass=file permissive=0
2019-06-05 14:22:36.418 1157-1157/? W//system/bin/chargemonitor: Waited for hwservicemanager.ready for a second, waiting another...
2019-06-05 14:22:36.419 1157-1157/? E/libc: Access denied finding property "hwservicemanager.ready"
2019-06-05 14:22:36.419 1157-1157/? E/libc: Access denied finding property "hwservicemanager.ready"
2019-06-05 14:22:36.444 864-864/? E/SDM: DisplayBase::BuildLayerStackStats: LayerStack layer_count: 6, app_layer_count: 5, gpu_target_index: 5, display type: 0
2019-06-05 14:22:36.578 864-864/? I/chatty: uid=1000(system) composer@2.1-se identical 4 lines
2019-06-05 14:22:36.611 864-864/? E/SDM: DisplayBase::BuildLayerStackStats: LayerStack layer_count: 6, app_layer_count: 5, gpu_target_index: 5, display type: 0
2019-06-05 14:22:36.777 15935-15935/? I/appproc: CLASSPATH=/system/framework/am.jar
2019-06-05 14:22:36.777 15935-15935/? I/appproc: Command=/system/bin/app_process /system/bin com.android.commands.am.Am broadcast -n com.topjohnwu.magisk/a.h --user 0 -f 0x00000020 -a android.intent.action.REBOOT --es action log --ei from.uid 2000 --ei to.uid 0 --ei pid 15929 --ei policy 2 --es command ls -l / --ez notify true 
2019-06-05 14:22:36.777 15935-15935/? D/AndroidRuntime: >>>>>> START com.android.internal.os.RuntimeInit uid 0 <<<<<<
2019-06-05 14:22:36.781 15935-15935/? I/AndroidRuntime: readDownloadBoosterConfig: 'false'
2019-06-05 14:22:36.931 15935-15935/? V/HwFrameworkFactory: : successes to get AllImpl object and return....
2019-06-05 14:22:36.944 15935-15935/? I/HWSERVICES: hwnative_get_component_register:libdrmbitmap,JNI
2019-06-05 14:22:36.969 15935-15935/? E/Zygote: register_com_android_internal_os_Zygote num = 0
2019-06-05 14:22:36.984 15935-15935/? D/AndroidRuntime: Calling main entry com.android.commands.am.Am
2019-06-05 14:22:36.987 1101-1173/? W/SchedPolicy: add_tid_to_cgroup failed to write '15943' (Permission denied); fd=6
2019-06-05 14:22:36.987 1101-1173/? E/SchedPolicy: set_cpuset_policy failed err=-22, tid=15943, policy=1
2019-06-05 14:22:36.988 1101-1173/? W/SchedPolicy: add_tid_to_cgroup failed to write '15943' (Permission denied); fd=6
2019-06-05 14:22:36.989 1101-1173/? E/SchedPolicy: set_cpuset_policy failed err=-22, tid=15943, policy=1
2019-06-05 14:22:36.989 1101-1173/? W/SchedPolicy: add_tid_to_cgroup failed to write '15944' (Permission denied); fd=6
2019-06-05 14:22:36.989 1101-1173/? E/SchedPolicy: set_cpuset_policy failed err=-22, tid=15944, policy=1
2019-06-05 14:22:36.989 1101-1173/? W/SchedPolicy: add_tid_to_cgroup failed to write '15944' (Permission denied); fd=6
2019-06-05 14:22:36.989 1101-1173/? E/SchedPolicy: set_cpuset_policy failed err=-22, tid=15944, policy=1
2019-06-05 14:22:37.003 13994-13994/? D/HwRTBlurUtils: check blur style for HwToast-Toast, themeResId : 0x0103013f, context : a.e@da8688b, Nhwext : 6, get Blur : disable with , android.graphics.drawable.NinePatchDrawable@aa601dc
2019-06-05 14:22:37.074 9938-10763/? V/BroadcastQueue: Finished with ordered broadcast BroadcastRecord{34eb677 u0 android.intent.action.REBOOT}
2019-06-05 14:22:37.075 15935-15935/? D/AndroidRuntime: Shutting down VM
2019-06-05 14:22:37.419 1157-1157/? W//system/bin/chargemonitor: Waited for hwservicemanager.ready for a second, waiting another...
2019-06-05 14:22:37.419 1157-1157/? E/libc: Access denied finding property "hwservicemanager.ready"
2019-06-05 14:22:37.419 1157-1157/? E/libc: Access denied finding property "hwservicemanager.ready"
2019-06-05 14:22:38.000 9938-10110/? D/HwBatteryService: onUEvent fcpStatus = 0,scpStatus =0,ovpStatus=0
2019-06-05 14:22:38.160 15964-15964/? I/appproc: CLASSPATH=/system/framework/am.jar
2019-06-05 14:22:38.160 15964-15964/? I/appproc: Command=/system/bin/app_process /system/bin com.android.commands.am.Am broadcast -n com.topjohnwu.magisk/a.h --user 0 -f 0x00000020 -a android.intent.action.REBOOT --es action log --ei from.uid 2000 --ei to.uid 0 --ei pid 15958 --ei policy 2 --es command ls -l -d /bugreports/ --ez notify true 
2019-06-05 14:22:38.160 15964-15964/? D/AndroidRuntime: >>>>>> START com.android.internal.os.RuntimeInit uid 0 <<<<<<
2019-06-05 14:22:38.164 15964-15964/? I/AndroidRuntime: readDownloadBoosterConfig: 'false'
2019-06-05 14:22:38.309 15964-15964/? V/HwFrameworkFactory: : successes to get AllImpl object and return....
2019-06-05 14:22:38.321 15964-15964/? I/HWSERVICES: hwnative_get_component_register:libdrmbitmap,JNI
2019-06-05 14:22:38.347 15964-15964/? E/Zygote: register_com_android_internal_os_Zygote num = 0
2019-06-05 14:22:38.362 15964-15964/? D/AndroidRuntime: Calling main entry com.android.commands.am.Am
2019-06-05 14:22:38.364 1101-1173/? W/SchedPolicy: add_tid_to_cgroup failed to write '15972' (Permission denied); fd=6
2019-06-05 14:22:38.364 1101-1173/? E/SchedPolicy: set_cpuset_policy failed err=-22, tid=15972, policy=1
2019-06-05 14:22:38.366 1101-1173/? W/SchedPolicy: add_tid_to_cgroup failed to write '15972' (Permission denied); fd=6
2019-06-05 14:22:38.366 1101-1173/? E/SchedPolicy: set_cpuset_policy failed err=-22, tid=15972, policy=1
2019-06-05 14:22:38.368 1101-1173/? W/SchedPolicy: add_tid_to_cgroup failed to write '15973' (Permission denied); fd=6
2019-06-05 14:22:38.368 1101-1173/? E/SchedPolicy: set_cpuset_policy failed err=-22, tid=15973, policy=1
2019-06-05 14:22:38.370 1101-1173/? W/SchedPolicy: add_tid_to_cgroup failed to write '15973' (Permission denied); fd=6
2019-06-05 14:22:38.371 1101-1173/? E/SchedPolicy: set_cpuset_policy failed err=-22, tid=15973, policy=1
2019-06-05 14:22:38.383 13994-13994/? D/HwRTBlurUtils: check blur style for HwToast-Toast, themeResId : 0x0103013f, context : a.e@da8688b, Nhwext : 6, get Blur : disable with , android.graphics.drawable.NinePatchDrawable@96802e5
2019-06-05 14:22:38.417 1157-1157/? W/chargemonitor: type=1400 audit(0.0:4251): avc: denied { read } for name="u:object_r:hwservicemanager_prop:s0" dev="tmpfs" ino=496 scontext=u:r:chargemonitor:s0 tcontext=u:object_r:hwservicemanager_prop:s0 tclass=file permissive=0
2019-06-05 14:22:38.419 1157-1157/? W//system/bin/chargemonitor: Waited for hwservicemanager.ready for a second, waiting another...
2019-06-05 14:22:38.420 1157-1157/? E/libc: Access denied finding property "hwservicemanager.ready"
2019-06-05 14:22:38.457 9938-13920/? V/BroadcastQueue: Finished with ordered broadcast BroadcastRecord{3c58e02 u0 android.intent.action.REBOOT}
2019-06-05 14:22:38.457 15964-15964/? D/AndroidRuntime: Shutting down VM
2019-06-05 14:22:39.307 15984-15984/? I/appproc: CLASSPATH=/system/framework/am.jar
2019-06-05 14:22:39.307 15984-15984/? I/appproc: Command=/system/bin/app_process /system/bin com.android.commands.am.Am broadcast -n com.topjohnwu.magisk/a.h --user 0 -f 0x00000020 -a android.intent.action.REBOOT --es action log --ei from.uid 2000 --ei to.uid 0 --ei pid 15978 --ei policy 2 --es command ls -l -d /charger/ --ez notify true 
2019-06-05 14:22:39.307 15984-15984/? D/AndroidRuntime: >>>>>> START com.android.internal.os.RuntimeInit uid 0 <<<<<<
2019-06-05 14:22:39.311 15984-15984/? I/AndroidRuntime: readDownloadBoosterConfig: 'false'
2019-06-05 14:22:39.417 1157-1157/? W/chargemonitor: type=1400 audit(0.0:4253): avc: denied { read } for name="u:object_r:hwservicemanager_prop:s0" dev="tmpfs" ino=496 scontext=u:r:chargemonitor:s0 tcontext=u:object_r:hwservicemanager_prop:s0 tclass=file permissive=0
2019-06-05 14:22:39.420 1157-1157/? W//system/bin/chargemonitor: Waited for hwservicemanager.ready for a second, waiting another...
2019-06-05 14:22:39.420 1157-1157/? E/libc: Access denied finding property "hwservicemanager.ready"
2019-06-05 14:22:39.420 1157-1157/? E/libc: Access denied finding property "hwservicemanager.ready"
2019-06-05 14:22:39.454 15984-15984/? V/HwFrameworkFactory: : successes to get AllImpl object and return....
2019-06-05 14:22:39.467 15984-15984/? I/HWSERVICES: hwnative_get_component_register:libdrmbitmap,JNI
2019-06-05 14:22:39.493 15984-15984/? E/Zygote: register_com_android_internal_os_Zygote num = 0
2019-06-05 14:22:39.508 15984-15984/? D/AndroidRuntime: Calling main entry com.android.commands.am.Am
2019-06-05 14:22:39.509 1101-1173/? W/SchedPolicy: add_tid_to_cgroup failed to write '15993' (Permission denied); fd=6
2019-06-05 14:22:39.509 1101-1173/? E/SchedPolicy: set_cpuset_policy failed err=-22, tid=15993, policy=1
2019-06-05 14:22:39.510 1101-1173/? W/SchedPolicy: add_tid_to_cgroup failed to write '15993' (Permission denied); fd=6
2019-06-05 14:22:39.510 1101-1173/? E/SchedPolicy: set_cpuset_policy failed err=-22, tid=15993, policy=1
2019-06-05 14:22:39.511 1101-1173/? W/SchedPolicy: add_tid_to_cgroup failed to write '15994' (Permission denied); fd=6
2019-06-05 14:22:39.511 1101-1173/? E/SchedPolicy: set_cpuset_policy failed err=-22, tid=15994, policy=1
2019-06-05 14:22:39.513 1101-1173/? W/SchedPolicy: add_tid_to_cgroup failed to write '15994' (Permission denied); fd=6
2019-06-05 14:22:39.513 1101-1173/? E/SchedPolicy: set_cpuset_policy failed err=-22, tid=15994, policy=1
2019-06-05 14:22:39.520 864-864/? E/SDM: DisplayBase::BuildLayerStackStats: LayerStack layer_count: 5, app_layer_count: 4, gpu_target_index: 4, display type: 0
2019-06-05 14:22:39.529 13994-13994/? D/HwRTBlurUtils: check blur style for HwToast-Toast, themeResId : 0x0103013f, context : a.e@da8688b, Nhwext : 6, get Blur : disable with , android.graphics.drawable.NinePatchDrawable@44931ba
2019-06-05 14:22:39.536 864-864/? E/SDM: DisplayBase::BuildLayerStackStats: LayerStack layer_count: 5, app_layer_count: 4, gpu_target_index: 4, display type: 0
2019-06-05 14:22:39.603 9938-10763/? V/BroadcastQueue: Finished with ordered broadcast BroadcastRecord{cf50749 u0 android.intent.action.REBOOT}
2019-06-05 14:22:39.553 864-864/? E/SDM: DisplayBase::BuildLayerStackStats: LayerStack layer_count: 5, app_layer_count: 4, gpu_target_index: 4, display type: 0
2019-06-05 14:22:39.603 15984-15984/? D/AndroidRuntime: Shutting down VM
2019-06-05 14:22:39.970 864-864/? E/SDM: DisplayBase::BuildLayerStackStats: LayerStack layer_count: 5, app_layer_count: 4, gpu_target_index: 4, display type: 0
2019-06-05 14:22:39.970 864-864/? E/SDM: Strategy::GetNextStrategy: All strategy failed, falling back to GPU
2019-06-05 14:22:40.091 10490-10630/? I/DeviceStateService: no user activity duration:180002 timeout:32000
2019-06-05 14:22:40.094 10490-10630/? W/APwTrigger: block the screen timeout, no user activity duraion:180002
2019-06-05 14:22:40.201 9938-10356/? E/Watchdog: Failed to write to /sys/kernel/hungtask/vm_heart
    java.io.FileNotFoundException: /sys/kernel/hungtask/vm_heart (Permission denied)
        at java.io.FileOutputStream.open0(Native Method)
        at java.io.FileOutputStream.open(FileOutputStream.java:287)
        at java.io.FileOutputStream.<init>(FileOutputStream.java:223)
        at java.io.FileOutputStream.<init>(FileOutputStream.java:110)
        at com.android.server.Watchdog.writeHungtask(Watchdog.java:790)
        at com.android.server.Watchdog.run(Watchdog.java:542)
2019-06-05 14:22:40.203 9938-10003/? I/EventHub: EventHub monitor: no key events in the past 243s, no motion events in the past 180s
```

**Comment by SergeyAppDroid** [comment]
@oleavr 
is something wrong here?
```
HWAUM-Q:/ # echo 0 > /sys/fs/selinux/enforce
1|HWAUM-Q:/ # getenforce
Enforcing
```

**Comment by oleavr** [comment]
> I think you need to pay attention to Chinese manufacturers in the future. The popularity of these devices is much more than any Google/Nexus ))

Sure. Google/Nexus is the #1 priority at work though, and considering that I'm already spread way too thin just maintaining Frida on all currently supported platforms and architectures, adding even more to that already crazy burden is not going to happen anytime soon ***unless*** somebody from the community helps out. (Maybe that's you? ;-) ) 

> What does this error mean?
> `remote_write PTRACE_POKEDATA head failed: 5`

It means that this failed: https://github.com/frida/frida-core/blob/a37515462d792dcade5c7b567c2e70633a400107/src/linux/frida-helper-backend-glue.c#L2446

Would you be interested in building Frida yourself and adding some temporary logging to explore it further?

> is something wrong here?
> ```
> HWAUM-Q:/ # echo 0 > /sys/fs/selinux/enforce
> 1|HWAUM-Q:/ # getenforce
> Enforcing
> ```

The OEM's kernel is probably configured to not support disabling SELinux. However, SELinux is not a problem, as we dynamically insert some additional rules into the running kernel's policy:
https://github.com/frida/frida-core/blob/a37515462d792dcade5c7b567c2e70633a400107/lib/selinux/src/patch.c#L44-L57

**Comment by SergeyAppDroid** [comment]
@oleavr Are you sure that the problem is definitely not SELinux? Because I can not change this parameter in any way (
Which way then to explore?

**Comment by oleavr** [comment]
> Are you sure that the problem is definitely not SELinux?

No, but there's usually an audit error in logcat when SELinux is blocking it. Look for lines containing `permissive=0`. FWIW I did see some errors like that in the log you shared, but they were for an unrelated process.

**Comment by SergeyAppDroid** [comment]
@oleavr Can you give me an example of such an error? So I understand what to look for

**Comment by oleavr** [comment]
Two random examples:
```
E audit   : type=1400 msg=audit(1111111111.222:333): avc:  denied  { write } for  pid=1234 comm="app_process" name="system@framework@boot.art" dev="mmcblk0p28" ino=54 scontext=u:r:shell:s0 tcontext=u:object_r:dalvikcache_data_file:s0 tclass=file permissive=0
E audit   : type=1400 msg=audit(1111111111.222:333): avc:  denied  { write } for  pid=1234 comm="main" name="arm" dev="mmcblk0p28" ino=52 scontext=u:r:shell:s0 tcontext=u:object_r:dalvikcache_data_file:s0 tclass=dir permissive=0
```

**Comment by SergeyAppDroid** [comment]
many similar errors:
```
2019-06-05 19:03:53.694 884-884/? W/chargemonitor: type=1400 audit(0.0:3448): avc: denied { read } for name="u:object_r:hwservicemanager_prop:s0" dev="tmpfs" ino=16389 scontext=u:r:chargemonitor:s0 tcontext=u:object_r:hwservicemanager_prop:s0 tclass=file permissive=0
2019-06-05 19:03:53.694 884-884/? W/chargemonitor: type=1400 audit(0.0:3449): avc: denied { read } for name="u:object_r:hwservicemanager_prop:s0" dev="tmpfs" ino=16389 scontext=u:r:chargemonitor:s0 tcontext=u:object_r:hwservicemanager_prop:s0 tclass=file permissive=0
```

**Comment by uhzpp** [comment]
HUAWEI device need to recompile the kernel and enable the option `CONFIG_HUAWEI_PTRACE_POKE_ON`

**Comment by smaznet** [comment]
@unzpp how?
where is that in source?
Are you tested?

**Comment by smaznet** [comment]
> HUAWEI device need to recompile the kernel and enable the option `CONFIG_HUAWEI_PTRACE_POKE_ON`

are you tested it?
i tested it but not working

**Comment by smaznet** [comment]
> HUAWEI device need to recompile the kernel and enable the option `CONFIG_HUAWEI_PTRACE_POKE_ON`

Thank you :+1: 
 my problem resolved by doing that

**Comment by oleavr** [comment]
@smaznet @uhzpp If any of you would be willing to write a detailed guide and submit a PR for [frida-website](https://github.com/frida/frida-website/), that would be amazing! I'm sure a lot of other users are running into this and giving up. I personally only have "vanilla" Android devices to test on, so can't be of much help in documenting how to use Frida on other device flavors.

**Comment by zhaoyongping** [comment]
> > HUAWEI device need to recompile the kernel and enable the option `CONFIG_HUAWEI_PTRACE_POKE_ON`
> 
> Thank you 👍
> my problem resolved by doing that

How to recompile the kernel and enable the option CONFIG_HUAWEI_PTRACE_POKE_ON?
Thank you!

**Comment by smaznet** [comment]
Read README_Kernel.txt file of kernel

**Comment by Gunkkk** [comment]
> > HUAWEI device need to recompile the kernel and enable the option `CONFIG_HUAWEI_PTRACE_POKE_ON`
> 
> Thank you 👍
> my problem resolved by doing that

I change the kernel and the issue still be there，is there any trick？

**Comment by salbatore** [comment]
I use Frida quite a bit and I have a fairly advanced knowledge of Android. This error has started to appear in an Android simulator on Mac. An emulator that Frida has been using for several years. The problem has started to appear when installing a new application on the device itself. I have been investigating, but understand that the problem is not with the device.

```
Traceback (most recent call last):
  File "/interceptor/main.py", line 184, in <module>
    session = device.attach("com.car2go")
  File "/usr/local/lib/python3.9/site-packages/frida/core.py", line 26, in wrapper
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/frida/core.py", line 156, in attach
    return Session(self._impl.attach(self._pid_of(target), *args, **kwargs))
frida.NotSupportedError: remote_write PTRACE_POKEDATA head failed: 5

```

Has anyone been able to fix the problem without compiling the kernel?

Off topic: Ole, you are a genious.

**Comment by salbatore** [comment]
Now i receive:

`frida.NotSupportedError: remote_call PTRACE_CONT wait failed: 1
`

**Comment by cafissimo** [comment]
> > HUAWEI device need to recompile the kernel and enable the option `CONFIG_HUAWEI_PTRACE_POKE_ON`
> 
> Thank you 👍 my problem resolved by doing that

Hello,
please could you kindly tell me for which device you recompiled kernel?
I have a  Huwarei P8 Lite 2017 dual SIM (hi6250 kirin 655) and I should recompile a kernel for that one, for Oreo firmware.
Of course, if you have one ready... plaese share :-)

**Comment by douggettemy88-svg** [comment]
> perhaps logging will be useful
> 
> ```
> 2019-06-05 14:22:26.413 1157-1157/? W//system/bin/chargemonitor: Waited for hwservicemanager.ready for a second, waiting another...
> 2019-06-05 14:22:26.414 1157-1157/? E/libc: Access denied finding property "hwservicemanager.ready"
> 2019-06-05 14:22:26.414 1157-1157/? E/libc: Access denied finding property "hwservicemanager.ready"
> 2019-06-05 14:22:27.414 1157-1157/? W//system/bin/chargemonitor: Waited for hwservicemanager.ready for a second, waiting another...
> 2019-06-05 14:22:27.414 1157-1157/? E/libc: Access denied finding property "hwservicemanager.ready"
> 2019-06-05 14:22:27.414 1157-1157/? E/libc: Access denied finding property "hwservicemanager.ready"
> 2019-06-05 14:22:28.413 1157-1157/? W/chargemonitor: type=1400 audit(0.0:4219): avc: denied { read } for name="u:object_r:hwservicemanager_prop:s0" dev="tmpfs" ino=496 scontext=u:r:chargemonitor:s0 tcontext=u:object_r:hwservicemanager_prop:s0 tclass=file permissive=0
> 2019-06-05 14:22:28.415 1157-1157/? W//system/bin/chargemonitor: Waited for hwservicemanager.ready for a second, waiting another...
> 2019-06-05 14:22:28.415 1157-1157/? E/libc: Access denied finding property "hwservicemanager.ready"
> 2019-06-05 14:22:28.415 1157-1157/? E/libc: Access denied finding property "hwservicemanager.ready"
> 2019-06-05 14:22:29.416 1157-1157/? W//system/bin/chargemonitor: Waited for hwservicemanager.ready for a second, waiting another...
> 2019-06-05 14:22:29.416 1157-1157/? E/libc: Access denied finding property "hwservicemanager.ready"
> 2019-06-05 14:22:29.416 1157-1157/? E/libc: Access denied finding property "hwservicemanager.ready"
> 2019-06-05 14:22:29.979 9938-10110/? D/HwBatteryService: onUEvent fcpStatus = 0,scpStatus =0,ovpStatus=0
> 2019-06-05 14:22:30.413 1157-1157/? I/chatty: uid=1000(system) /system/bin/chargemonitor identical 2 lines
> 2019-06-05 14:22:30.413 1157-1157/? W/chargemonitor: type=1400 audit(0.0:4224): avc: denied { read } for name="u:object_r:hwservicemanager_prop:s0" dev="tmpfs" ino=496 scontext=u:r:chargemonitor:s0 tcontext=u:object_r:hwservicemanager_prop:s0 tclass=file permissive=0
> 2019-06-05 14:22:30.416 1157-1157/? W//system/bin/chargemonitor: Waited for hwservicemanager.ready for a second, waiting another...
> 2019-06-05 14:22:30.416 1157-1157/? E/libc: Access denied finding property "hwservicemanager.ready"
> 2019-06-05 14:22:30.416 1157-1157/? E/libc: Access denied finding property "hwservicemanager.ready"
> 2019-06-05 14:22:31.416 1157-1157/? W//system/bin/chargemonitor: Waited for hwservicemanager.ready for a second, waiting another...
> 2019-06-05 14:22:31.417 1157-1157/? E/libc: Access denied finding property "hwservicemanager.ready"
> 2019-06-05 14:22:31.417 1157-1157/? E/libc: Access denied finding property "hwservicemanager.ready"
> 2019-06-05 14:22:32.417 1157-1157/? W//system/bin/chargemonitor: Waited for hwservicemanager.ready for a second, waiting another...
> 2019-06-05 14:22:32.417 1157-1157/? E/libc: Access denied finding property "hwservicemanager.ready"
> 2019-06-05 14:22:32.417 1157-1157/? E/libc: Access denied finding property "hwservicemanager.ready"
> 2019-06-05 14:22:33.417 1157-1157/? W//system/bin/chargemonitor: Waited for hwservicemanager.ready for a second, waiting another...
> 2019-06-05 14:22:33.417 1157-1157/? E/libc: Access denied finding property "hwservicemanager.ready"
> 2019-06-05 14:22:33.417 1157-1157/? E/libc: Access denied finding property "hwservicemanager.ready"
> 2019-06-05 14:22:34.417 1157-1157/? W//system/bin/chargemonitor: Waited for hwservicemanager.ready for a second, waiting another...
> 2019-06-05 14:22:34.418 1157-1157/? E/libc: Access denied finding property "hwservicemanager.ready"
> 2019-06-05 14:22:34.418 1157-1157/? E/libc: Access denied finding property "hwservicemanager.ready"
> 2019-06-05 14:22:34.803 888-1076/? I/qti_sensors_hal: [LightSensor]processReportInd: the cycle luxValue ItemData[0]:230000,ItemData[1]:9d, lux:35.000000,cct:0.002396
> 2019-06-05 14:22:35.418 1157-1157/? W//system/bin/chargemonitor: Waited for hwservicemanager.ready for a second, waiting another...
> 2019-06-05 14:22:35.418 1157-1157/? E/libc: Access denied finding property "hwservicemanager.ready"
> 2019-06-05 14:22:35.418 1157-1157/? E/libc: Access denied finding property "hwservicemanager.ready"
> 2019-06-05 14:22:35.662 15913-15913/? I/appproc: CLASSPATH=/system/framework/am.jar
> 2019-06-05 14:22:35.663 15913-15913/? I/appproc: Command=/system/bin/app_process /system/bin com.android.commands.am.Am broadcast -n com.topjohnwu.magisk/a.h --user 0 -f 0x00000020 -a android.intent.action.REBOOT --es action log --ei from.uid 2000 --ei to.uid 0 --ei pid 15907 --ei policy 2 --es command id --ez notify true 
> 2019-06-05 14:22:35.663 15913-15913/? D/AndroidRuntime: >>>>>> START com.android.internal.os.RuntimeInit uid 0 <<<<<<
> 2019-06-05 14:22:35.667 15913-15913/? I/AndroidRuntime: readDownloadBoosterConfig: 'false'
> 2019-06-05 14:22:35.814 15913-15913/? V/HwFrameworkFactory: : successes to get AllImpl object and return....
> 2019-06-05 14:22:35.828 15913-15913/? I/HWSERVICES: hwnative_get_component_register:libdrmbitmap,JNI
> 2019-06-05 14:22:35.854 15913-15913/? E/Zygote: register_com_android_internal_os_Zygote num = 0
> 2019-06-05 14:22:35.869 15913-15913/? D/AndroidRuntime: Calling main entry com.android.commands.am.Am
> 2019-06-05 14:22:35.872 1101-1173/? W/SchedPolicy: add_tid_to_cgroup failed to write '15921' (Permission denied); fd=6
> 2019-06-05 14:22:35.872 1101-1173/? E/SchedPolicy: set_cpuset_policy failed err=-22, tid=15921, policy=1
> 2019-06-05 14:22:35.873 1101-1173/? W/SchedPolicy: add_tid_to_cgroup failed to write '15921' (Permission denied); fd=6
> 2019-06-05 14:22:35.873 1101-1173/? E/SchedPolicy: set_cpuset_policy failed err=-22, tid=15921, policy=1
> 2019-06-05 14:22:35.874 1101-1173/? W/SchedPolicy: add_tid_to_cgroup failed to write '15922' (Permission denied); fd=6
> 2019-06-05 14:22:35.874 1101-1173/? E/SchedPolicy: set_cpuset_policy failed err=-22, tid=15922, policy=1
> 2019-06-05 14:22:35.874 1101-1173/? W/SchedPolicy: add_tid_to_cgroup failed to write '15922' (Permission denied); fd=6
> 2019-06-05 14:22:35.874 1101-1173/? E/SchedPolicy: set_cpuset_policy failed err=-22, tid=15922, policy=1
> 2019-06-05 14:22:35.904 13994-13994/? D/HwRTBlurUtils: check blur style for HwToast-Toast, themeResId : 0x0103013f, context : a.e@da8688b, Nhwext : 6, get Blur : disable with , android.graphics.drawable.NinePatchDrawable@b119b2d
> 2019-06-05 14:22:35.979 9938-13920/? V/BroadcastQueue: Finished with ordered broadcast BroadcastRecord{786767f u0 android.intent.action.REBOOT}
> 2019-06-05 14:22:35.981 15913-15913/? D/AndroidRuntime: Shutting down VM
> 2019-06-05 14:22:35.981 13994-15598/? D/OpenGLRenderer:   HWUI Binary is  disabled
> 2019-06-05 14:22:35.981 10490-10889/? I/ash: view add pid:13994 uid:10099
> 2019-06-05 14:22:35.985 9938-13920/? V/WindowManager: Adding Window{415fb9b u0 Toast} to WindowToken{4e78b38 android.os.Binder@7a91695}
> 2019-06-05 14:22:35.986 9938-13920/? V/WindowManager: addWindow: New client android.os.BinderProxy@41e33aa: window=Window{415fb9b u0 Toast} Callers=com.android.server.wm.HwWindowManagerService.addWindow:585 com.android.server.wm.Session.addToDisplay:199 android.view.IWindowSession$Stub.onTransact:124 com.android.server.wm.Session.onTransact:161 android.os.Binder.execTransact:675 
> 2019-06-05 14:22:35.987 13994-15598/? D/OpenGLRenderer:   HWUI Binary is  disabled
> 2019-06-05 14:22:35.989 13994-13994/? W/ViewRootImpl[Toast]: EGLdebug relayoutWindow Surface isSurface(name=null)  (appName =com.topjohnwu.magisk) ( mSurfaceControllerIsValid =false) (mNativeObject  =0)/@0x3a7564f,viewVisibility is0
> 2019-06-05 14:22:35.995 430-430/? I/SELinux: avc:  received policyload notice (seqno=3)
> 2019-06-05 14:22:35.996 430-430/? E/SELinux: avc:  denied  { find } for interface=vendor.huawei.hardware.hwsched::ISched pid=907 scontext=u:r:surfaceflinger:s0 tcontext=u:object_r:default_android_hwservice:s0 tclass=hwservice_manager
> 2019-06-05 14:22:35.996 907-907/? E/BufferQueueProducer: [] Can not get hwsched service
> 2019-06-05 14:22:35.998 9938-13920/? W/WindowManager: EGLdebug Created surface WindowStateAnimator{8518711 Toast}
> 2019-06-05 14:22:36.000 9938-13920/? W/WindowManager: EGLdebug surface name is Toastsurface is Surface(name=null)  (appName =null) ( mSurfaceControllerIsValid =true) (mNativeObject  =7c31ad6000)/@0xa03e076
> 2019-06-05 14:22:36.006 13994-13994/? W/ViewRootImpl[Toast]: EGLdebug relayoutWindow Surface isSurface(name=null)  (appName =com.topjohnwu.magisk) ( mSurfaceControllerIsValid =true) (mNativeObject  =7c61a63000)/@0x3a7564f,relayoutResult is7
> 2019-06-05 14:22:36.006 13994-13994/? W/ViewRootImpl[Toast]: EGLdebug Surface isSurface(name=null)  (appName =com.topjohnwu.magisk) ( mSurfaceControllerIsValid =true) (mNativeObject  =7c61a63000)/@0x3a7564f
> 2019-06-05 14:22:36.010 864-864/? E/SDM: DisplayBase::BuildLayerStackStats: LayerStack layer_count: 5, app_layer_count: 4, gpu_target_index: 4, display type: 0
> 2019-06-05 14:22:36.011 864-864/? E/SDM: Strategy::GetNextStrategy: All strategy failed, falling back to GPU
> 2019-06-05 14:22:36.028 864-864/? E/SDM: DisplayBase::BuildLayerStackStats: LayerStack layer_count: 5, app_layer_count: 4, gpu_target_index: 4, display type: 0
> 2019-06-05 14:22:36.028 864-864/? E/SDM: Strategy::GetNextStrategy: All strategy failed, falling back to GPU
> 2019-06-05 14:22:36.035 9938-13920/? D/WindowManager: finishDrawingWindow: Window{415fb9b u0 Toast} mDrawState=DRAW_PENDING
> 2019-06-05 14:22:36.044 864-864/? E/SDM: DisplayBase::BuildLayerStackStats: LayerStack layer_count: 5, app_layer_count: 4, gpu_target_index: 4, display type: 0
> 2019-06-05 14:22:36.044 864-864/? E/SDM: Strategy::GetNextStrategy: All strategy failed, falling back to GPU
> 2019-06-05 14:22:36.061 1013-3037/? D/DE N SR: setXnit:1056: R=32768 G=32768 B=32768 len=12
> 2019-06-05 14:22:36.061 864-864/? E/SDM: DisplayBase::BuildLayerStackStats: LayerStack layer_count: 6, app_layer_count: 5, gpu_target_index: 5, display type: 0
> 2019-06-05 14:22:36.062 1013-2325/? D/DE N ^XNIT: onChange:35: DE_SCENE_ACTION_XNIT_CHANGE COMPONENT_XCC mode:0x1f
> 2019-06-05 14:22:36.062 1013-2325/? D/DE N HWC: apply:87: FEATURE_XCC: <mode:0x1e>
> 2019-06-05 14:22:36.062 1013-2325/? D/DE N HW: setEffect:71: FEATURE_XCC mode:0x1e size:12
> 2019-06-05 14:22:36.065 879-879/? D/DE H =KI: setXCC:93: 3d_color_temperature config: r=32768, g=32768, b=32768
> 2019-06-05 14:22:36.065 879-879/? D/DE H =KI: setXCC:103: Set pp data of 3d_color_temperature successful!
> 2019-06-05 14:22:36.077 864-864/? E/SDM: DisplayBase::BuildLayerStackStats: LayerStack layer_count: 6, app_layer_count: 5, gpu_target_index: 5, display type: 0
> 2019-06-05 14:22:36.210 864-864/? I/chatty: uid=1000(system) composer@2.1-se identical 5 lines
> 2019-06-05 14:22:36.244 864-864/? E/SDM: DisplayBase::BuildLayerStackStats: LayerStack layer_count: 6, app_layer_count: 5, gpu_target_index: 5, display type: 0
> 2019-06-05 14:22:36.276 9702-9706/? E/libnav: CablComputeBacklightLevel(): UpdateType = DifferentSceneUpdate
> 2019-06-05 14:22:36.278 864-864/? E/SDM: DisplayBase::BuildLayerStackStats: LayerStack layer_count: 6, app_layer_count: 5, gpu_target_index: 5, display type: 0
> 2019-06-05 14:22:36.344 864-864/? E/SDM: DisplayBase::BuildLayerStackStats: LayerStack layer_count: 6, app_layer_count: 5, gpu_target_index: 5, display type: 0
> 2019-06-05 14:22:36.359 9938-10221/? D/LightsService: Excessive delay setting light: 66ms
> 2019-06-05 14:22:36.361 864-864/? E/SDM: DisplayBase::BuildLayerStackStats: LayerStack layer_count: 6, app_layer_count: 5, gpu_target_index: 5, display type: 0
> 2019-06-05 14:22:36.378 864-864/? I/chatty: uid=1000(system) composer@2.1-se identical 1 line
> 2019-06-05 14:22:36.411 864-864/? E/SDM: DisplayBase::BuildLayerStackStats: LayerStack layer_count: 6, app_layer_count: 5, gpu_target_index: 5, display type: 0
> 2019-06-05 14:22:36.418 1157-1157/? W//system/bin/chargemonitor: Waited for hwservicemanager.ready for a second, waiting another...
> 2019-06-05 14:22:36.419 1157-1157/? E/libc: Access denied finding property "hwservicemanager.ready"
> 2019-06-05 14:22:36.419 1157-1157/? E/libc: Access denied finding property "hwservicemanager.ready"
> 2019-06-05 14:22:36.413 1157-1157/? W/chargemonitor: type=1400 audit(0.0:4239): avc: denied { read } for name="u:object_r:hwservicemanager_prop:s0" dev="tmpfs" ino=496 scontext=u:r:chargemonitor:s0 tcontext=u:object_r:hwservicemanager_prop:s0 tclass=file permissive=0
> 2019-06-05 14:22:36.418 1157-1157/? W//system/bin/chargemonitor: Waited for hwservicemanager.ready for a second, waiting another...
> 2019-06-05 14:22:36.419 1157-1157/? E/libc: Access denied finding property "hwservicemanager.ready"
> 2019-06-05 14:22:36.419 1157-1157/? E/libc: Access denied finding property "hwservicemanager.ready"
> 2019-06-05 14:22:36.444 864-864/? E/SDM: DisplayBase::BuildLayerStackStats: LayerStack layer_count: 6, app_layer_count: 5, gpu_target_index: 5, display type: 0
> 2019-06-05 14:22:36.578 864-864/? I/chatty: uid=1000(system) composer@2.1-se identical 4 lines
> 2019-06-05 14:22:36.611 864-864/? E/SDM: DisplayBase::BuildLayerStackStats: LayerStack layer_count: 6, app_layer_count: 5, gpu_target_index: 5, display type: 0
> 2019-06-05 14:22:36.777 15935-15935/? I/appproc: CLASSPATH=/system/framework/am.jar
> 2019-06-05 14:22:36.777 15935-15935/? I/appproc: Command=/system/bin/app_process /system/bin com.android.commands.am.Am broadcast -n com.topjohnwu.magisk/a.h --user 0 -f 0x00000020 -a android.intent.action.REBOOT --es action log --ei from.uid 2000 --ei to.uid 0 --ei pid 15929 --ei policy 2 --es command ls -l / --ez notify true 
> 2019-06-05 14:22:36.777 15935-15935/? D/AndroidRuntime: >>>>>> START com.android.internal.os.RuntimeInit uid 0 <<<<<<
> 2019-06-05 14:22:36.781 15935-15935/? I/AndroidRuntime: readDownloadBoosterConfig: 'false'
> 2019-06-05 14:22:36.931 15935-15935/? V/HwFrameworkFactory: : successes to get AllImpl object and return....
> 2019-06-05 14:22:36.944 15935-15935/? I/HWSERVICES: hwnative_get_component_register:libdrmbitmap,JNI
> 2019-06-05 14:22:36.969 15935-15935/? E/Zygote: register_com_android_internal_os_Zygote num = 0
> 2019-06-05 14:22:36.984 15935-15935/? D/AndroidRuntime: Calling main entry com.android.commands.am.Am
> 2019-06-05 14:22:36.987 1101-1173/? W/SchedPolicy: add_tid_to_cgroup failed to write '15943' (Permission denied); fd=6
> 2019-06-05 14:22:36.987 1101-1173/? E/SchedPolicy: set_cpuset_policy failed err=-22, tid=15943, policy=1
> 2019-06-05 14:22:36.988 1101-1173/? W/SchedPolicy: add_tid_to_cgroup failed to write '15943' (Permission denied); fd=6
> 2019-06-05 14:22:36.989 1101-1173/? E/SchedPolicy: set_cpuset_policy failed err=-22, tid=15943, policy=1
> 2019-06-05 14:22:36.989 1101-1173/? W/SchedPolicy: add_tid_to_cgroup failed to write '15944' (Permission denied); fd=6
> 2019-06-05 14:22:36.989 1101-1173/? E/SchedPolicy: set_cpuset_policy failed err=-22, tid=15944, policy=1
> 2019-06-05 14:22:36.989 1101-1173/? W/SchedPolicy: add_tid_to_cgroup failed to write '15944' (Permission denied); fd=6
> 2019-06-05 14:22:36.989 1101-1173/? E/SchedPolicy: set_cpuset_policy failed err=-22, tid=15944, policy=1
> 2019-06-05 14:22:37.003 13994-13994/? D/HwRTBlurUtils: check blur style for HwToast-Toast, themeResId : 0x0103013f, context : a.e@da8688b, Nhwext : 6, get Blur : disable with , android.graphics.drawable.NinePatchDrawable@aa601dc
> 2019-06-05 14:22:37.074 9938-10763/? V/BroadcastQueue: Finished with ordered broadcast BroadcastRecord{34eb677 u0 android.intent.action.REBOOT}
> 2019-06-05 14:22:37.075 15935-15935/? D/AndroidRuntime: Shutting down VM
> 2019-06-05 14:22:37.419 1157-1157/? W//system/bin/chargemonitor: Waited for hwservicemanager.ready for a second, waiting another...
> 2019-06-05 14:22:37.419 1157-1157/? E/libc: Access denied finding property "hwservicemanager.ready"
> 2019-06-05 14:22:37.419 1157-1157/? E/libc: Access denied finding property "hwservicemanager.ready"
> 2019-06-05 14:22:38.000 9938-10110/? D/HwBatteryService: onUEvent fcpStatus = 0,scpStatus =0,ovpStatus=0
> 2019-06-05 14:22:38.160 15964-15964/? I/appproc: CLASSPATH=/system/framework/am.jar
> 2019-06-05 14:22:38.160 15964-15964/? I/appproc: Command=/system/bin/app_process /system/bin com.android.commands.am.Am broadcast -n com.topjohnwu.magisk/a.h --user 0 -f 0x00000020 -a android.intent.action.REBOOT --es action log --ei from.uid 2000 --ei to.uid 0 --ei pid 15958 --ei policy 2 --es command ls -l -d /bugreports/ --ez notify true 
> 2019-06-05 14:22:38.160 15964-15964/? D/AndroidRuntime: >>>>>> START com.android.internal.os.RuntimeInit uid 0 <<<<<<
> 2019-06-05 14:22:38.164 15964-15964/? I/AndroidRuntime: readDownloadBoosterConfig: 'false'
> 2019-06-05 14:22:38.309 15964-15964/? V/HwFrameworkFactory: : successes to get AllImpl object and return....
> 2019-06-05 14:22:38.321 15964-15964/? I/HWSERVICES: hwnative_get_component_register:libdrmbitmap,JNI
> 2019-06-05 14:22:38.347 15964-15964/? E/Zygote: register_com_android_internal_os_Zygote num = 0
> 2019-06-05 14:22:38.362 15964-15964/? D/AndroidRuntime: Calling main entry com.android.commands.am.Am
> 2019-06-05 14:22:38.364 1101-1173/? W/SchedPolicy: add_tid_to_cgroup failed to write '15972' (Permission denied); fd=6
> 2019-06-05 14:22:38.364 1101-1173/? E/SchedPolicy: set_cpuset_policy failed err=-22, tid=15972, policy=1
> 2019-06-05 14:22:38.366 1101-1173/? W/SchedPolicy: add_tid_to_cgroup failed to write '15972' (Permission denied); fd=6
> 2019-06-05 14:22:38.366 1101-1173/? E/SchedPolicy: set_cpuset_policy failed err=-22, tid=15972, policy=1
> 2019-06-05 14:22:38.368 1101-1173/? W/SchedPolicy: add_tid_to_cgroup failed to write '15973' (Permission denied); fd=6
> 2019-06-05 14:22:38.368 1101-1173/? E/SchedPolicy: set_cpuset_policy failed err=-22, tid=15973, policy=1
> 2019-06-05 14:22:38.370 1101-1173/? W/SchedPolicy: add_tid_to_cgroup failed to write '15973' (Permission denied); fd=6
> 2019-06-05 14:22:38.371 1101-1173/? E/SchedPolicy: set_cpuset_policy failed err=-22, tid=15973, policy=1
> 2019-06-05 14:22:38.383 13994-13994/? D/HwRTBlurUtils: check blur style for HwToast-Toast, themeResId : 0x0103013f, context : a.e@da8688b, Nhwext : 6, get Blur : disable with , android.graphics.drawable.NinePatchDrawable@96802e5
> 2019-06-05 14:22:38.417 1157-1157/? W/chargemonitor: type=1400 audit(0.0:4251): avc: denied { read } for name="u:object_r:hwservicemanager_prop:s0" dev="tmpfs" ino=496 scontext=u:r:chargemonitor:s0 tcontext=u:object_r:hwservicemanager_prop:s0 tclass=file permissive=0
> 2019-06-05 14:22:38.419 1157-1157/? W//system/bin/chargemonitor: Waited for hwservicemanager.ready for a second, waiting another...
> 2019-06-05 14:22:38.420 1157-1157/? E/libc: Access denied finding property "hwservicemanager.ready"
> 2019-06-05 14:22:38.457 9938-13920/? V/BroadcastQueue: Finished with ordered broadcast BroadcastRecord{3c58e02 u0 android.intent.action.REBOOT}
> 2019-06-05 14:22:38.457 15964-15964/? D/AndroidRuntime: Shutting down VM
> 2019-06-05 14:22:39.307 15984-15984/? I/appproc: CLASSPATH=/system/framework/am.jar
> 2019-06-05 14:22:39.307 15984-15984/? I/appproc: Command=/system/bin/app_process /system/bin com.android.commands.am.Am broadcast -n com.topjohnwu.magisk/a.h --user 0 -f 0x00000020 -a android.intent.action.REBOOT --es action log --ei from.uid 2000 --ei to.uid 0 --ei pid 15978 --ei policy 2 --es command ls -l -d /charger/ --ez notify true 
> 2019-06-05 14:22:39.307 15984-15984/? D/AndroidRuntime: >>>>>> START com.android.internal.os.RuntimeInit uid 0 <<<<<<
> 2019-06-05 14:22:39.311 15984-15984/? I/AndroidRuntime: readDownloadBoosterConfig: 'false'
> 2019-06-05 14:22:39.417 1157-1157/? W/chargemonitor: type=1400 audit(0.0:4253): avc: denied { read } for name="u:object_r:hwservicemanager_prop:s0" dev="tmpfs" ino=496 scontext=u:r:chargemonitor:s0 tcontext=u:object_r:hwservicemanager_prop:s0 tclass=file permissive=0
> 2019-06-05 14:22:39.420 1157-1157/? W//system/bin/chargemonitor: Waited for hwservicemanager.ready for a second, waiting another...
> 2019-06-05 14:22:39.420 1157-1157/? E/libc: Access denied finding property "hwservicemanager.ready"
> 2019-06-05 14:22:39.420 1157-1157/? E/libc: Access denied finding property "hwservicemanager.ready"
> 2019-06-05 14:22:39.454 15984-15984/? V/HwFrameworkFactory: : successes to get AllImpl object and return....
> 2019-06-05 14:22:39.467 15984-15984/? I/HWSERVICES: hwnative_get_component_register:libdrmbitmap,JNI
> 2019-06-05 14:22:39.493 15984-15984/? E/Zygote: register_com_android_internal_os_Zygote num = 0
> 2019-06-05 14:22:39.508 15984-15984/? D/AndroidRuntime: Calling main entry com.android.commands.am.Am
> 2019-06-05 14:22:39.509 1101-1173/? W/SchedPolicy: add_tid_to_cgroup failed to write '15993' (Permission denied); fd=6
> 2019-06-05 14:22:39.509 1101-1173/? E/SchedPolicy: set_cpuset_policy failed err=-22, tid=15993, policy=1
> 2019-06-05 14:22:39.510 1101-1173/? W/SchedPolicy: add_tid_to_cgroup failed to write '15993' (Permission denied); fd=6
> 2019-06-05 14:22:39.510 1101-1173/? E/SchedPolicy: set_cpuset_policy failed err=-22, tid=15993, policy=1
> 2019-06-05 14:22:39.511 1101-1173/? W/SchedPolicy: add_tid_to_cgroup failed to write '15994' (Permission denied); fd=6
> 2019-06-05 14:22:39.511 1101-1173/? E/SchedPolicy: set_cpuset_policy failed err=-22, tid=15994, policy=1
> 2019-06-05 14:22:39.513 1101-1173/? W/SchedPolicy: add_tid_to_cgroup failed to write '15994' (Permission denied); fd=6
> 2019-06-05 14:22:39.513 1101-1173/? E/SchedPolicy: set_cpuset_policy failed err=-22, tid=15994, policy=1
> 2019-06-05 14:22:39.520 864-864/? E/SDM: DisplayBase::BuildLayerStackStats: LayerStack layer_count: 5, app_layer_count: 4, gpu_target_index: 4, display type: 0
> 2019-06-05 14:22:39.529 13994-13994/? D/HwRTBlurUtils: check blur style for HwToast-Toast, themeResId : 0x0103013f, context : a.e@da8688b, Nhwext : 6, get Blur : disable with , android.graphics.drawable.NinePatchDrawable@44931ba
> 2019-06-05 14:22:39.536 864-864/? E/SDM: DisplayBase::BuildLayerStackStats: LayerStack layer_count: 5, app_layer_count: 4, gpu_target_index: 4, display type: 0
> 2019-06-05 14:22:39.603 9938-10763/? V/BroadcastQueue: Finished with ordered broadcast BroadcastRecord{cf50749 u0 android.intent.action.REBOOT}
> 2019-06-05 14:22:39.553 864-864/? E/SDM: DisplayBase::BuildLayerStackStats: LayerStack layer_count: 5, app_layer_count: 4, gpu_target_index: 4, display type: 0
> 2019-06-05 14:22:39.603 15984-15984/? D/AndroidRuntime: Shutting down VM
> 2019-06-05 14:22:39.970 864-864/? E/SDM: DisplayBase::BuildLayerStackStats: LayerStack layer_count: 5, app_layer_count: 4, gpu_target_index: 4, display type: 0
> 2019-06-05 14:22:39.970 864-864/? E/SDM: Strategy::GetNextStrategy: All strategy failed, falling back to GPU
> 2019-06-05 14:22:40.091 10490-10630/? I/DeviceStateService: no user activity duration:180002 timeout:32000
> 2019-06-05 14:22:40.094 10490-10630/? W/APwTrigger: block the screen timeout, no user activity duraion:180002
> 2019-06-05 14:22:40.201 9938-10356/? E/Watchdog: Failed to write to /sys/kernel/hungtask/vm_heart
>     java.io.FileNotFoundException: /sys/kernel/hungtask/vm_heart (Permission denied)
>         at java.io.FileOutputStream.open0(Native Method)
>         at java.io.FileOutputStream.open(FileOutputStream.java:287)
>         at java.io.FileOutputStream.<init>(FileOutputStream.java:223)
>         at java.io.FileOutputStream.<init>(FileOutputStream.java:110)
>         at com.android.server.Watchdog.writeHungtask(Watchdog.java:790)
>         at com.android.server.Watchdog.run(Watchdog.java:542)
> 2019-06-05 14:22:40.203 9938-10003/? I/EventHub: EventHub monitor: no key events in the past 243s, no motion events in the past 180s
> ```
